$(document).ready(function() {

	/* nav dropdown menu */
	if ($(window).width() > 768) {
		$('#navbar .nav').removeClass('animated bounceInDown');
		$('ul.nav li.dropdown').hover(function() {
			//$(this).find('.dropdown-menu').stop(true, true).fadeIn();
			//$(this).find('.dropdown-menu').stop(true, true).slideDown();
			$(this).find('.dropdown-menu').removeClass('animated flipOutY').addClass('animated rubberBand');
			$(this).addClass('open');
		}, function() {
			//$(this).find('.dropdown-menu').stop(true, true).fadeOut();
			//$(this).find('.dropdown-menu').stop(true, true).slideUp();
			//$(this).find('.dropdown-menu').removeClass('animated flipInY').addClass('animated flipOutY');
			$(this).removeClass('open');
		});
	} else {
		$('#navbar .nav').addClass('animated bounceInDown');
	}

	/* remove focus from bootstrap btn */
	$('.btn').focus(function(event) {
		event.target.blur();
	});

	$('.btn-default, .form-control').hover(function(event) {
		//$(this).addClass('animated jello');
		//$(this).addClass('animated rubberBand');
	}, function(){
		//$(this).removeClass('animated jello');
		//$(this).removeClass('animated rubberBand');
	});

	/* remove empty p tag */
	$('p').each(function() {
		var $this = $(this);
		if ($this.html().replace(/\s|&nbsp;/g, '').length == 0)
			$this.remove();
	});

	/* remove error image */
	$("img").error(function() {
		$(this).hide();
	});

	/* window scroll */
	// $fn.scrollSpeed(step, speed, easing);
	jQuery.scrollSpeed(100, 600);

	/* fancybox */
	$(".fancybox").fancybox({
		openEffect : 'elastic',
		closeEffect : 'elastic',
		helpers : {
			overlay : {
				locked : false
			}
		}
	});

	/* flexslider */
	$('.flexslider').flexslider({
		namespace : "flex-", //{NEW} String: Prefix string attached to the class of every element generated by the plugin
		selector : ".slides > li", //{NEW} Selector: Must match a simple pattern. '{container} > {slide}' -- Ignore pattern at your own peril
		animation : "fade", //String: Select your animation type, "fade" or "slide"
		easing : "swing", //{NEW} String: Determines the easing method used in jQuery transitions. jQuery easing plugin is supported!
		direction : "horizontal", //String: Select the sliding direction, "horizontal" or "vertical"
		reverse : false, //{NEW} Boolean: Reverse the animation direction
		animationLoop : true, //Boolean: Should the animation loop? If false, directionNav will received "disable" classes at either end
		smoothHeight : false, //{NEW} Boolean: Allow height of the slider to animate smoothly in horizontal mode
		startAt : 0, //Integer: The slide that the slider should start on. Array notation (0 = first slide)
		slideshow : true, //Boolean: Animate slider automatically
		slideshowSpeed : 7000, //Integer: Set the speed of the slideshow cycling, in milliseconds
		animationSpeed : 600, //Integer: Set the speed of animations, in milliseconds
		initDelay : 0, //{NEW} Integer: Set an initialization delay, in milliseconds
		randomize : false, //Boolean: Randomize slide order

		// Usability features
		pauseOnAction : true, //Boolean: Pause the slideshow when interacting with control elements, highly recommended.
		pauseOnHover : false, //Boolean: Pause the slideshow when hovering over slider, then resume when no longer hovering
		useCSS : true, //{NEW} Boolean: Slider will use CSS3 transitions if available
		touch : true, //{NEW} Boolean: Allow touch swipe navigation of the slider on touch-enabled devices
		video : false, //{NEW} Boolean: If using video in the slider, will prevent CSS3 3D Transforms to avoid graphical glitches

		// Primary Controls
		controlNav : true, //Boolean: Create navigation for paging control of each clide? Note: Leave true for manualControls usage
		directionNav : false, //Boolean: Create navigation for previous/next navigation? (true/false)
		prevText : "Previous", //String: Set the text for the "previous" directionNav item
		nextText : "Next", //String: Set the text for the "next" directionNav item

		// Secondary Navigation
		keyboard : true, //Boolean: Allow slider navigating via keyboard left/right keys
		multipleKeyboard : false, //{NEW} Boolean: Allow keyboard navigation to affect multiple sliders. Default behavior cuts out keyboard navigation with more than one slider present.
		mousewheel : false, //{UPDATED} Boolean: Requires jquery.mousewheel.js (https://github.com/brandonaaron/jquery-mousewheel) - Allows slider navigating via mousewheel
		pausePlay : false, //Boolean: Create pause/play dynamic element
		pauseText : 'Pause', //String: Set the text for the "pause" pausePlay item
		playText : 'Play', //String: Set the text for the "play" pausePlay item

		// Special properties
		controlsContainer : "", //{UPDATED} Selector: USE CLASS SELECTOR. Declare which container the navigation elements should be appended too. Default container is the FlexSlider element. Example use would be ".flexslider-container". Property is ignored if given element is not found.
		manualControls : "", //Selector: Declare custom control navigation. Examples would be ".flex-control-nav li" or "#tabs-nav li img", etc. The number of elements in your controlNav should match the number of slides/tabs.
		sync : "", //{NEW} Selector: Mirror the actions performed on this slider with another slider. Use with care.
		asNavFor : "", //{NEW} Selector: Internal property exposed for turning the slider into a thumbnail navigation for another slider

		// Carousel Options
		itemWidth : 0, //{NEW} Integer: Box-model width of individual carousel items, including horizontal borders and padding.
		itemMargin : 0, //{NEW} Integer: Margin between carousel items.
		minItems : 0, //{NEW} Integer: Minimum number of carousel items that should be visible. Items will resize fluidly when below this.
		maxItems : 0, //{NEW} Integer: Maxmimum number of carousel items that should be visible. Items will resize fluidly when above this limit.
		move : 0, //{NEW} Integer: Number of carousel items that should move on animation. If 0, slider will move all visible items.

		// Callback API
		start : function() {
		}, //Callback: function(slider) - Fires when the slider loads the first slide
		before : function() {
		}, //Callback: function(slider) - Fires asynchronously with each slider animation
		after : function() {
		}, //Callback: function(slider) - Fires after each slider animation completes
		end : function() {
		}, //Callback: function(slider) - Fires when the slider reaches the last slide (asynchronous)
		added : function() {
		}, //{NEW} Callback: function(slider) - Fires after a slide is added
		removed : function() {
		} //{NEW} Callback: function(slider) - Fires after a slide is removed
	});

	/* disable right click */
	document.addEventListener("contextmenu", function(e) {
		e.preventDefault();
	}, false);

	/* disable developer mode (f12) */
	document.addEventListener("keydown", function(event) {
		event = (event || window.event);
		if (event.keyCode == 123) {
			return false;
		} else if (event.ctrlKey && event.shiftKey && event.keyCode == 73) {
			return false;
			// Prevent from ctrl+shift+i
		}
	}, false);

});

/* contact form verify */
function verify() {
	/* Reset modal content */
	$('.modal-title').html(null);
	$('.modal-body').html(null);
	/* Check form fields */
	var error = 0;
	var elm = ["name", "email", "message"];
	for (var i = 0; i < elm.length; i++) {
		if (document.getElementById(elm[i]).value.trim() == null || document.getElementById(elm[i]).value.trim() == '' || document.getElementById(elm[i]).value.trim() == '0') {
			/*document.getElementById(elm[i]).value = '';
			document.getElementById(elm[i]).classList.add('error');*/
			document.getElementById(elm[i]).style.outline = '1px solid red';
			error = 1;
			if (elm[i] == 'msg_type' || elm[i] == 'test') {
				$('#' + elm[i] + '').selectpicker('setStyle', 'btn-danger');
			}
		} else {
			//document.getElementById(elm[i]).classList.remove('error');
			document.getElementById(elm[i]).style.outline = 'none';
			if (elm[i] == 'msg_type' || elm[i] == 'test') {
				$('#' + elm[i] + '').selectpicker('setStyle', 'btn-danger', 'remove');
				$('#' + elm[i] + '').selectpicker('refresh');
			}
		}
		if (elm[i] == 'email_address') {
			if (document.getElementById('email_address').value.trim() != '') {
				var emailReg1 = /(@.*@)|(\.\.)|(@\.)|(\.@)|(^\.)/;
				var emailReg2 = /^.+\@(\[?)[a-zA-Z0-9\-\.]+\.([a-zA-Z]{2,6}|[0-9]{1,3})(\]?)$/;
				if (!(!emailReg1.test(document.getElementById('email_address').value.trim()) && emailReg2.test(document.getElementById('email_address').value.trim()))) {
					/*document.getElementById(elm[i]).value = '';
					document.getElementById(elm[i]).classList.add('error');*/
					document.getElementById('email').style.outline = '1px solid red';
					error = 1;
				} else {
					//document.getElementById(elm[i]).classList.remove('error');
					document.getElementById(elm[i]).style.outline = 'none';
				}
			}
		}
	}
	if (error == 0) {
		//this.form.submit();
		//document.getElementById('kontakt').submit();
		var data = $('#contact').serialize();
		$.ajax({
			type : 'post',
			dataType : 'json',
			data : data,
			url : 'email.php',
			success : function(response) {
				if (response.error == 0) {
					$('.flip-container').toggleClass('hover');
				}
			}
		});
		return false;
	} else {
		//alert('All fields are requested!');
		$('.modal-title').html('Error!');
		$('.modal-body').html('* Please fill in the required fields.');
		$('#myModal').modal('show');
		return false;
	}
}